export const API_BASE_URL = 'http://localhost:5000/api'
export const PROVINCE_ENDPOINT = '/province'
export const CITY_ENDPOINT = '/city'
export const COMPANY_ENDPOINT = '/company'
export const ROUTE_ENDPOINT = '/route'
